# --- START OF FILE: src/capitalguard/domain/ports.py ---
from typing import Protocol, Optional, List, Tuple, Any
from .entities import Recommendation

class RecommendationRepoPort(Protocol):
    def add(self, rec: Recommendation) -> Recommendation: ...
    def get(self, rec_id: int) -> Optional[Recommendation]: ...
    def list_open(self, channel_id: int | None = None) -> List[Recommendation]: ...
    def list_all(self, channel_id: int | None = None) -> List[Recommendation]: ...
    def update(self, rec: Recommendation) -> Recommendation: ...
    def set_channel_message(self, rec_id: int, channel_id: int, message_id: int, published_at: Optional[Any] = None) -> Recommendation: ...

class NotifierPort(Protocol):
    def send_message(self, text: str, chat_id: Optional[str | int] = None) -> None: ...
    def post_recommendation_card(self, rec: Recommendation) -> Optional[Tuple[int, int]]: ...
    def edit_recommendation_card(self, rec: Recommendation) -> bool: ...
# --- END OF FILE ---