#--- START OF FILE: src/capitalguard/domain/ports.py ---
from typing import Protocol, Optional, List, Tuple
from .entities import Recommendation

class RecommendationRepoPort(Protocol):
    def add(self, rec: Recommendation) -> Recommendation: ...
    def get(self, rec_id: int) -> Optional[Recommendation]: ...
    def list_open(self) -> List[Recommendation]: ...
    def list_all(self, symbol: Optional[str] = None, status: Optional[str] = None) -> List[Recommendation]: ...
    def update(self, rec: Recommendation) -> Recommendation: ...
    def set_channel_message(self, rec_id: int, channel_id: int, message_id: int) -> Recommendation: ...

class NotifierPort(Protocol):
    def post_recommendation_card(self, rec: Recommendation) -> Optional[Tuple[int, int]]: ...
    def edit_recommendation_card(self, rec: Recommendation) -> bool: ...
    def send_admin_alert(self, text: str) -> None: ...


class PriceFeedPort(Protocol):
    """Read-only market price contract; execution and order placement are out of scope."""

    def get_price(self, symbol: str) -> float: ...
#--- END OF FILE ---
