"""Add is_shadow column to recommendations table

Revision ID: 20251007_add_is_shadow
Revises: 20251008_full_unified_schema_v2
Create Date: 2025-10-08 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251007_add_is_shadow'
down_revision = '20251008_full_unified_schema_v2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Adding 'is_shadow' column to 'recommendations' table...")
    op.add_column('recommendations', sa.Column('is_shadow', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    print("'is_shadow' column added successfully.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Dropping 'is_shadow' column from 'recommendations' table...")
    op.drop_column('recommendations', 'is_shadow')
    print("'is_shadow' column dropped successfully.")
    # ### end Alembic commands ###