"""
Add Watchlist/Activated portfolio layers and channel auditing schema.

✅ THE FIX (R1-S1): This migration applies the core "Trader-First" schema:
1. Creates the new 'watched_channels' table for channel auditing.
2. Updates the 'usertradestatus' enum to include 'WATCHLIST' and 'PENDING_ACTIVATION'.
3. Alters the 'user_trades' table:
    - Casts old 'OPEN' status to new 'ACTIVATED' status.
    - Sets 'WATCHLIST' as the new default.
    - Adds 'original_published_at', 'activated_at', and 'watched_channel_id' (FK).

Revision ID: 20251110_add_watchlist_layer
Revises: 20251104_optimize_parsing_db_performance
Create Date: 2025-11-10 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251110_add_watchlist_layer'
down_revision = '20251104_optimize_parsing_db_performance' # This should be the last migration file in the previous state
branch_labels = None
depends_on = None

# Define the new ENUM type
new_enum_name = 'usertradestatus'
new_enum_values = ('WATCHLIST', 'PENDING_ACTIVATION', 'ACTIVATED', 'CLOSED')
new_enum_type = sa.Enum(*new_enum_values, name=new_enum_name)

# Define the old ENUM type (as it was)
old_enum_name = 'usertradestatus'
old_enum_values = ('OPEN', 'CLOSED')
old_enum_type = sa.Enum(*old_enum_values, name=old_enum_name)


def upgrade() -> None:
    # ### Commands auto generated by Alembic - adjusted for ENUM migration ###
    
    # 1. Create the new watched_channels table
    op.create_table('watched_channels',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('telegram_channel_id', sa.BigInteger(), nullable=False),
        sa.Column('channel_title', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'telegram_channel_id', name='uq_user_channel_watch')
    )
    op.create_index(op.f('ix_watched_channels_telegram_channel_id'), 'watched_channels', ['telegram_channel_id'], unique=False)
    op.create_index(op.f('ix_watched_channels_user_id'), 'watched_channels', ['user_id'], unique=False)

    # 2. Add new columns to user_trades
    op.add_column('user_trades', sa.Column('watched_channel_id', sa.Integer(), nullable=True))
    op.add_column('user_trades', sa.Column('original_published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_trades', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_user_trades_watched_channel', 
        'user_trades', 'watched_channels', 
        ['watched_channel_id'], ['id'], 
        ondelete='SET NULL'
    )
    op.create_index(op.f('ix_user_trades_watched_channel_id'), 'user_trades', ['watched_channel_id'], unique=False)

    # 3. Perform the ENUM migration (PostgreSQL specific)
    # Rename old enum
    op.execute(f"ALTER TYPE {old_enum_name} RENAME TO {old_enum_name}_old")
    
    # Create new enum
    new_enum_type.create(op.get_bind())
    
    # Alter the column type, casting old values to new values
    # We map old 'OPEN' to 'ACTIVATED' as this is the logical equivalent
    op.alter_column('user_trades', 'status',
        type_=new_enum_type,
        postgresql_using=f"""
            CASE 
                WHEN status::text = 'OPEN' THEN 'ACTIVATED'::usertradestatus
                WHEN status::text = 'CLOSED' THEN 'CLOSED'::usertradestatus
                ELSE 'WATCHLIST'::usertradestatus
            END
        """,
        nullable=False,
        # Set new default for all future rows
        server_default='WATCHLIST'
    )
    
    # Drop the old enum
    op.execute(f"DROP TYPE {old_enum_name}_old")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### Commands auto generated by Alembic - adjusted for ENUM migration ###
    
    # 1. Revert ENUM changes (PostgreSQL specific)
    # We must define the *old* type (which is the *new* type in the upgrade)
    # and the *new* type (which is the *old* type in the upgrade)
    
    # Rename current enum (the new one)
    op.execute(f"ALTER TYPE {new_enum_name} RENAME TO {new_enum_name}_new")
    
    # Re-create the old enum
    old_enum_type.create(op.get_bind())
    
    # Alter column back, casting 'ACTIVATED' to 'OPEN'
    op.alter_column('user_trades', 'status',
        type_=old_enum_type,
        postgresql_using=f"""
            CASE
                WHEN status::text = 'ACTIVATED' THEN 'OPEN'::usertradestatus
                WHEN status::text = 'CLOSED' THEN 'CLOSED'::usertradestatus
                ELSE 'OPEN'::usertradestatus
            END
        """,
        nullable=False,
        server_default='OPEN' # Restore old default
    )
    
    # Drop the new enum
    op.execute(f"DROP TYPE {new_enum_name}_new")

    # 2. Drop new columns from user_trades
    op.drop_index(op.f('ix_user_trades_watched_channel_id'), table_name='user_trades')
    op.drop_constraint('fk_user_trades_watched_channel', 'user_trades', type_='foreignkey')
    op.drop_column('user_trades', 'activated_at')
    op.drop_column('user_trades', 'original_published_at')
    op.drop_column('user_trades', 'watched_channel_id')

    # 3. Drop the watched_channels table
    op.drop_index(op.f('ix_watched_channels_user_id'), table_name='watched_channels')
    op.drop_index(op.f('ix_watched_channels_telegram_channel_id'), table_name='watched_channels')
    op.drop_table('watched_channels')
    
    # ### end Alembic commands ###