#--- START OF FILE: alembic/versions/20250828_change_user_id_to_string.py ---
"""Change user_id in recommendations to String

Revision ID: 20250828_change_uid
Revises: 20250825_add_exit_price_closed_at
Create Date: 2025-08-28 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250828_change_uid'
down_revision = '20250825_add_exit_price_closed_at'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True,
               # This part is specific to PostgreSQL to cast the existing data
               postgresql_using='user_id::character varying')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'user_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               # This part is specific to PostgreSQL to cast the data back
               postgresql_using='user_id::bigint')
    # ### end Alembic commands ###
#--- END OF FILE ---