# --- START OF NEW MIGRATION FILE ---
"""Create published_messages table for multi-channel support

Revision ID: 20250909_1_create_piblished_message
Revises: 20250909_create_channels_table
Create Date: 2025

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250909_1_create_piblished_message' # 👈 استبدل هذا بالمعرف الذي ولّده Alembic
down_revision = '20250909_create_channels_table' # 👈 تأكد أن هذا هو آخر ملف هجرة لديك
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recommendation_id', sa.Integer(), nullable=False),
        sa.Column('telegram_channel_id', sa.BigInteger(), nullable=False),
        sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
        sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_messages_recommendation_id'), 'published_messages', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_published_messages_recommendation_id'), table_name='published_messages')
    op.drop_table('published_messages')
    # ### end Alembic commands ###
# --- END OF NEW MIGRATION FILE ---