import DashboardLayout from "@/components/DashboardLayout";
import { KpiCard, PreviewNotice, SectionTitle, StatusPill } from "@/components/finance-ui";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, DatabaseZap, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";

type ReviewBatch = { id: number; ref: string; status: string; source_kind: string; total_records: number; accepted_records: number; rejected_records: number };

export default function Admin() {
  const overview = trpc.capitalguard.admin.overview.useQuery();
  const batches = trpc.capitalguard.admin.historicalReviewBatches.useQuery();
  const operations = trpc.capitalguard.admin.operationsFeed.useQuery(undefined, { refetchInterval: 15_000 });
  const r5 = trpc.capitalguard.admin.r5Readiness.useQuery(undefined, { refetchInterval: 15_000 });
  const historicalQuality = trpc.capitalguard.admin.historicalTrustQuality.useQuery(undefined, { refetchInterval: 15_000 });
  const historicalReadiness = trpc.capitalguard.admin.historicalTrustReadiness.useQuery(undefined, { refetchInterval: 15_000 });
  const review = trpc.capitalguard.admin.reviewHistoricalBatch.useMutation({
    onSuccess: result => { toast.success(`تم تسجيل القرار: ${String(result.status ?? "COMPLETED")}`); void batches.refetch(); },
    onError: () => toast.error("رفض Core الأمر أو تعذر تنفيذ المراجعة."),
  });
  const ingest = trpc.capitalguard.admin.ingestHistoricalEvidence.useMutation({
    onSuccess: result => { toast.success(`اكتمل إدخال Evidence: ${String(result.ingested ?? 0)} سجل.`); void batches.refetch(); },
    onError: () => toast.error("لم يكتمل إدخال Evidence. بقيت البيانات الحية دون تغيير."),
  });
  const replayBinance = trpc.capitalguard.admin.replayHistoricalSignalFromBinance.useMutation({
    onSuccess: result => { toast.success(`اكتمل replay تاريخي: ${result.event_count} حدثاً. بقيت بوابة التصنيف والتجارة في HOLD.`); void historicalQuality.refetch(); void historicalReadiness.refetch(); },
    onError: () => toast.error("رفض Core إعادة البناء أو تعذر مصدر Binance. لم يُنشأ بديل صامت."),
  });
  const values = overview.data ?? { users: 0, channels: 0, pendingReviews: 0, connection: "pending" };
  const liveQueue = batches.data ?? [];
  const queue: ReviewBatch[] = liveQueue;
  const hasLiveConnection = batches.isSuccess;
  const confirmReview = (batch: ReviewBatch, approved: boolean) => {
    const verb = approved ? "اعتماد" : "رفض";
    if (window.confirm(`${verb} الدفعة ${batch.ref}؟ القرار نهائي في Core ويسجل في سجل التدقيق.`)) review.mutate({ batchId: batch.id, approved, note: `Owner review from CapitalGuard Web (${verb})` });
  };
  const confirmIngestion = (batch: ReviewBatch) => {
    if (window.confirm(`بدء إدخال Evidence للدفعة ${batch.ref}؟ لن يتم إنشاء توصيات أو صفقات حية.`)) ingest.mutate({ batchId: batch.id });
  };
  const confirmBinanceReplay = () => {
    const signalId = Number(window.prompt("رقم السجل التاريخي المراجع (signal_id):", ""));
    if (!Number.isSafeInteger(signalId) || signalId <= 0) return toast.error("يلزم رقم سجل تاريخي صحيح.");
    const start = window.prompt("بداية النطاق UTC بصيغة ISO:", new Date(Date.now() - 3_600_000).toISOString());
    const end = window.prompt("نهاية النطاق UTC بصيغة ISO:", new Date().toISOString());
    if (!start || !end || !window.confirm("سيجلب Core شموع Binance لهذا السجل المراجع فقط. لا ينشئ هذا توصية حية أو ترتيباً عاماً. متابعة؟")) return;
    replayBinance.mutate({ signalId, start, end, interval: "1m", limit: 1500 });
  };
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-[1380px]">
    <div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Operations Center</p><h1 className="text-3xl font-semibold">إدارة موثقة، لا تدخلات صامتة.</h1><p className="mt-2 text-sm text-muted-foreground">صلاحيات، مصادر، Owner Review وEvidence Ingestion ضمن مسار تدقيق واحد.</p></div>
    <PreviewNotice isLive={hasLiveConnection} />
    <div className="grid gap-4 md:grid-cols-4"><KpiCard label="المستخدمون" value={String(values.users)} icon={<UsersRound className="h-4 w-4"/>} tone="cyan"/><KpiCard label="القنوات" value={String(values.channels)} icon={<DatabaseZap className="h-4 w-4"/>} tone="violet"/><KpiCard label="مراجعات معلّقة" value={String(liveQueue.filter(batch => ["DRY_RUN", "REVIEW_REQUIRED"].includes(batch.status)).length)} icon={<ShieldCheck className="h-4 w-4"/>} tone="amber"/><KpiCard label="حالة الاتصال" value={batches.isSuccess ? "Ready" : batches.isError ? "Error" : "Pending"} icon={<BadgeCheck className="h-4 w-4"/>} tone="emerald"/></div>
    <section className="mt-6 rounded-3xl border border-white/8 bg-card/70 p-5"><SectionTitle eyebrow="Owner Review" title="طابور الاعتماد"/>{batches.isLoading ? <p className="py-8 text-sm text-muted-foreground">جارٍ تحميل طابور Core…</p> : batches.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب طابور Core الحي. لم تُعرض أي بيانات بديلة؛ راجع اتصال API وصلاحية المالك ثم أعد المحاولة.</p> : queue.length === 0 ? <p className="rounded-2xl border border-white/8 bg-white/[.025] p-4 text-sm text-muted-foreground">لا توجد دفعات تاريخية مؤهلة للمراجعة حالياً.</p> : <div className="space-y-3">{queue.map(batch => <div key={batch.ref} className="grid gap-3 rounded-2xl border border-white/7 bg-white/[.025] p-4 lg:grid-cols-[1.1fr_.9fr_.9fr_1fr_auto] lg:items-center"><div><p className="font-mono text-xs text-amber-200">{batch.ref}</p><p className="mt-1 text-sm font-medium">{batch.source_kind}</p><p className="mt-1 text-xs text-muted-foreground">مقبول {batch.accepted_records} · مرفوض {batch.rejected_records} · إجمالي {batch.total_records}</p></div><StatusPill value={batch.status}/><span className="text-xs text-muted-foreground">Historical only</span><span className="text-xs text-cyan-200">لا توصية حية ولا UserTrade</span><div className="flex flex-wrap gap-2">{["DRY_RUN", "REVIEW_REQUIRED"].includes(batch.status) ? <><Button size="sm" className="bg-emerald-400 text-slate-950 hover:bg-emerald-300" disabled={review.isPending} onClick={() => confirmReview(batch, true)}>اعتماد</Button><Button size="sm" variant="outline" className="border-rose-400/25 text-rose-200" disabled={review.isPending} onClick={() => confirmReview(batch, false)}>رفض</Button></> : null}{batch.status === "VALIDATED" ? <Button size="sm" className="bg-cyan-400 text-slate-950 hover:bg-cyan-300" disabled={ingest.isPending} onClick={() => confirmIngestion(batch)}>إدخال Evidence</Button> : null}</div></div>)}</div>}</section>
    <section className="mt-6 rounded-3xl border border-cyan-400/20 bg-cyan-400/[.035] p-5"><SectionTitle eyebrow="Historical Replay" title="إعادة بناء Binance المراجعة" action={<StatusPill value="HOLD"/>}/><p className="text-sm text-cyan-100">للمالك فقط: يتطلب Core Evidence مراجعاً ويجلب OHLCV مقيداً. لا يفعّل ترتيباً عاماً أو تداولاً أو نشر Outbox.</p><Button className="mt-4 bg-cyan-400 text-slate-950 hover:bg-cyan-300" disabled={replayBinance.isPending} onClick={confirmBinanceReplay}>{replayBinance.isPending ? "جارٍ تشغيل replay…" : "تشغيل replay من Binance"}</Button></section>
    <section className="mt-6 rounded-3xl border border-amber-400/20 bg-amber-400/[.045] p-5"><SectionTitle eyebrow="R5 Noncommercial Gate" title="حالة الجاهزية التجارية" action={<StatusPill value={r5.data?.status ?? "HOLD"}/>}/>{r5.isLoading ? <p className="py-4 text-sm text-muted-foreground">جارٍ تقييم حواجز R5 من Core…</p> : r5.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب حالة R5. لا يُفسر ذلك كموافقة تجارية.</p> : <><p className="text-sm text-amber-100">الدفع وCopy Trading معطلان صراحةً. تظل الحالة HOLD حتى اكتمال أدلة الاستعادة وفترة الاستقرار.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><KpiCard label="Outbox backlog" value={String(r5.data?.snapshot.outbox_backlog ?? 0)} icon={<DatabaseZap className="h-4 w-4"/>} tone="cyan"/><KpiCard label="Owner Review backlog" value={String(r5.data?.snapshot.owner_review_backlog ?? 0)} icon={<ShieldCheck className="h-4 w-4"/>} tone="amber"/><KpiCard label="Replay backlog" value={String(r5.data?.snapshot.replay_backlog ?? 0)} icon={<BadgeCheck className="h-4 w-4"/>} tone="violet"/></div><div className="mt-4 flex flex-wrap gap-2"><StatusPill value={r5.data?.execution_controls.auto_trade_enabled ? "AUTO_TRADE_ENABLED" : "AUTO_TRADE_DISABLED"}/><StatusPill value={r5.data?.execution_controls.trade_live_enabled ? "TRADE_LIVE_ENABLED" : "TRADE_LIVE_DISABLED"}/><StatusPill value={`OBSERVATION ${r5.data?.observation.elapsed_hours ?? 0}/${r5.data?.observation.required_hours ?? 0}H`}/>{r5.data?.reasons.map(reason => <StatusPill key={reason} value={reason}/>)}</div></>}</section>
    <section className="mt-6 rounded-3xl border border-white/8 bg-card/70 p-5"><SectionTitle eyebrow="Operations Feed" title="سجل الأحداث التشغيلي"/><div className="mb-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-rose-400/10 p-3 text-sm text-rose-100">حرج: {operations.data?.summary.critical ?? 0}</div><div className="rounded-xl bg-amber-400/10 p-3 text-sm text-amber-100">تحذير: {operations.data?.summary.warning ?? 0}</div><div className="rounded-xl bg-cyan-400/10 p-3 text-sm text-cyan-100">آخر 100 حدث: {operations.data?.summary.total ?? 0}</div></div>{operations.isLoading ? <p className="py-4 text-sm text-muted-foreground">جارٍ تحميل أحداث Core…</p> : operations.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب سجل الأحداث من Core. لا تُعرض بيانات بديلة.</p> : (operations.data?.events.length ?? 0) === 0 ? <p className="rounded-2xl border border-white/8 bg-white/[.025] p-4 text-sm text-muted-foreground">لا توجد أحداث تشغيلية حديثة. ستحدّث هذه المنطقة تلقائياً كل 15 ثانية أثناء فتح الصفحة.</p> : <div className="space-y-2">{operations.data?.events.map(event => <div key={event.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-white/8 bg-white/[.025] px-3 py-2 text-xs"><div className="flex items-center gap-2"><span className={event.severity === "critical" ? "text-rose-200" : event.severity === "warning" ? "text-amber-200" : "text-cyan-200"}>{event.severity.toUpperCase()}</span><span>{event.category} · {event.code}</span></div><div className="flex items-center gap-3 text-muted-foreground"><span className="font-mono">{event.record_ref}</span><span>{new Date(event.occurred_at).toLocaleString("ar-SA")}</span></div></div>)}</div>}</section>
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><Rule title="دور المدير" detail="تعتمد الدفعات عبر جلسة Telegram للمالك، ثم يعيد Core فحص هوية المالك ومفتاح الخدمة."/><Rule title="Evidence Ingestion" detail="يبدأ بعد Owner Review؛ يستخدم مفتاح idempotency وسجل تدقيق ولا يحول السجل إلى توصية حية."/><Rule title="حماية السمعة" detail="Financial Mismatch وTimeline Conflict لا يصبحان ranking-eligible تلقائيًا."/></section>
    <section className="mt-6 rounded-3xl border border-cyan-400/20 bg-cyan-400/[.035] p-5"><SectionTitle eyebrow="Historical Trust Quality" title="جودة دليل الثقة التاريخية" action={<StatusPill value={historicalQuality.data?.status ?? "HOLD"}/>}/>{historicalQuality.isLoading ? <p className="py-4 text-sm text-muted-foreground">جارٍ تدقيق جودة العينة ودليل السوق من Core…</p> : historicalQuality.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب تقرير الجودة. لا يعني ذلك أن العينة صالحة أو أن التصنيف مسموح.</p> : <><p className="text-sm text-cyan-100">لا يُعرض هنا أداء تسويقي؛ هذه قراءة تشغيلية لحجم العينة والإسناد ودليل إعادة البناء فقط.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><KpiCard label="إجمالي السجلات" value={String(historicalQuality.data?.quality.total_signals ?? 0)} icon={<DatabaseZap className="h-4 w-4"/>} tone="cyan"/><KpiCard label="تغطية OHLCV" value={`${historicalQuality.data?.quality.replay_coverage_percent ?? 0}%`} icon={<BadgeCheck className="h-4 w-4"/>} tone="violet"/><KpiCard label="إسنادات مراجعَة" value={String(historicalQuality.data?.quality.reviewed_attributions ?? 0)} icon={<ShieldCheck className="h-4 w-4"/>} tone="emerald"/><KpiCard label="مستبعد من الترتيب" value={String(historicalQuality.data?.quality.excluded_signals ?? 0)} icon={<UsersRound className="h-4 w-4"/>} tone="amber"/></div><div className="mt-4 flex flex-wrap gap-2"><StatusPill value={`REPLAY ${historicalQuality.data?.quality.verified_replay_events ?? 0}`}/><StatusPill value={`ARTIFACTS ${historicalQuality.data?.quality.market_evidence_artifacts ?? 0}`}/><StatusPill value={`PENDING ATTRIBUTION ${historicalQuality.data?.quality.pending_attributions ?? 0}`}/><StatusPill value={historicalQuality.data?.commercial_enabled ? "COMMERCIAL_ENABLED" : "NONCOMMERCIAL"}/></div></>}</section>
    <section className="mt-6 rounded-3xl border border-violet-400/20 bg-violet-400/[.035] p-5"><SectionTitle eyebrow="Historical Public Ranking Gate" title="بوابة اعتماد الثقة التاريخية" action={<StatusPill value={historicalReadiness.data?.status ?? "HOLD"}/>}/>{historicalReadiness.isLoading ? <p className="py-4 text-sm text-muted-foreground">جارٍ فحص بوابة اعتماد التصنيف التاريخي…</p> : historicalReadiness.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر فحص البوابة؛ يظل التصنيف العام في HOLD ولا يمكن تفسير الخطأ كموافقة.</p> : <><p className="text-sm text-violet-100">هذه البوابة لا تفعّل تجارة أو Copy Trading. التصنيف العام يبقى موقوفاً حتى اكتمال العينة والتغطية ومراجعة الإسناد وقرار التشغيل الصريح.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><KpiCard label="حجم العينة" value={String(historicalReadiness.data?.snapshot.sample_size ?? 0)} icon={<DatabaseZap className="h-4 w-4"/>} tone="violet"/><KpiCard label="تغطية replay" value={`${historicalReadiness.data?.snapshot.replay_coverage_percent ?? 0}%`} icon={<BadgeCheck className="h-4 w-4"/>} tone="cyan"/><KpiCard label="إسنادات مراجعة" value={String(historicalReadiness.data?.snapshot.reviewed_attributions ?? 0)} icon={<ShieldCheck className="h-4 w-4"/>} tone="emerald"/><KpiCard label="مراجعات معلقة" value={String(historicalReadiness.data?.snapshot.pending_attributions ?? 0)} icon={<UsersRound className="h-4 w-4"/>} tone="amber"/></div><div className="mt-4 flex flex-wrap gap-2">{historicalReadiness.data?.reasons.map(reason => <StatusPill key={reason} value={reason}/>)}</div></>}</section>
  </div></DashboardLayout>;
}

function Rule({ title, detail }: { title: string; detail: string }) { return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
