import DashboardLayout from "@/components/DashboardLayout";
import { SectionTitle, StatusPill } from "@/components/finance-ui";
import { trpc } from "@/lib/trpc";
import { BarChart3, GitCompareArrows, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

export default function Analysts() {
  const analysts = trpc.capitalguard.discoverAnalysts.useQuery();
  const [selected, setSelected] = useState<string[]>([]);
  const rows = analysts.data?.items ?? [];
  const selectedRows = useMemo(() => rows.filter(row => selected.includes(row.analyst_code ?? row.public_ref ?? "")), [rows, selected]);
  const toggle = (code: string) => setSelected(current => current.includes(code) ? current.filter(item => item !== code) : current.length < 3 ? [...current, code] : current);
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-[1380px]"><div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Analyst Discovery</p><h1 className="text-3xl font-semibold">اكتشف الأداء. ثم قارن السياق.</h1><p className="mt-2 text-sm text-muted-foreground">المقارنة تعتمد بيانات Core العامة فقط؛ وتبقى أهلية الترتيب مرتبطة بالعينة والتحقق.</p></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><AnalystSignal icon={<ShieldCheck/>} label="قابلون للترتيب" value={String(rows.filter(row => row.eligible_for_ranking).length)}/><AnalystSignal icon={<BarChart3/>} label="محللون في Core" value={String(rows.length)}/><AnalystSignal icon={<GitCompareArrows/>} label="مختارون للمقارنة" value={String(selected.length)}/></div>
    <section className="rounded-3xl border border-white/8 bg-card/70 p-5"><SectionTitle title="لوحة المحللين" action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><Search className="h-4 w-4"/>اختر حتى ثلاثة محللين للمقارنة</div>}/>{analysts.isLoading ? <p className="py-8 text-sm text-muted-foreground">جارٍ تحميل المحللين من Core…</p> : analysts.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب بيانات المحللين الحية. لم تُعرض بيانات بديلة.</p> : rows.length === 0 ? <p className="rounded-2xl border border-white/8 bg-white/[.025] p-4 text-sm text-muted-foreground">لا توجد ملفات محللين عامة متاحة حالياً.</p> : <div className="grid gap-4 lg:grid-cols-3">{rows.map(analyst => { const code = analyst.analyst_code ?? analyst.public_ref ?? analyst.public_name; return <article key={code} className={"rounded-2xl border bg-white/[.025] p-5 transition " + (selected.includes(code) ? "border-cyan-400/40" : "border-white/8 hover:border-cyan-400/25")}><div className="flex items-start justify-between"><div><p className="font-mono text-[11px] text-cyan-300">{code}</p><h3 className="mt-2 text-lg font-semibold">{analyst.public_name}</h3><p className="mt-1 text-xs text-muted-foreground">حدّثت قبل {analyst.freshness_days ?? "—"} يوم</p></div><StatusPill value={analyst.eligible_for_ranking ? "verified" : "low_sample"}/></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric label="Win Rate" value={`${analyst.win_rate_pct.toFixed(1)}%`}/><Metric label="PnL" value={`${analyst.total_pnl_pct.toFixed(2)}%`}/><Metric label="Drawdown" value={`${analyst.max_drawdown_pct.toFixed(2)}%`}/></div><div className="mt-4 flex items-center justify-between"><p className="text-xs text-muted-foreground">Sample Size: {analyst.sample_size}</p><button onClick={() => toggle(code)} className="rounded-lg bg-white/5 px-2.5 py-1.5 text-xs text-cyan-200">{selected.includes(code) ? "إزالة" : "قارن"}</button></div></article>; })}</div>}</section>
    {selectedRows.length >= 2 ? <section className="mt-6 rounded-3xl border border-cyan-400/15 bg-gradient-to-l from-cyan-400/[.08] to-violet-400/[.07] p-5"><SectionTitle eyebrow="Compare Analysts" title="نتيجة المقارنة الحية"/><div className="grid gap-3 md:grid-cols-3">{[...selectedRows].sort((a, b) => b.total_pnl_pct - a.total_pnl_pct).map((row, index) => <div key={row.analyst_code ?? row.public_ref ?? row.public_name} className="rounded-2xl border border-white/8 bg-background/40 p-4"><p className="font-mono text-xs text-cyan-200">{row.analyst_code ?? row.public_ref}</p><p className="mt-2 text-lg font-semibold">{index === 0 ? "الصدارة الحالية" : "ضمن المقارنة"}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Metric label="PnL" value={`${row.total_pnl_pct.toFixed(2)}%`}/><Metric label="Win Rate" value={`${row.win_rate_pct.toFixed(1)}%`}/></div><p className="mt-3 text-xs text-muted-foreground">Sample: {row.sample_size} · DD: {row.max_drawdown_pct.toFixed(2)}%</p></div>)}</div></section> : null}
  </div></DashboardLayout>;
}
function AnalystSignal({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-white/8 bg-card/70 p-4"><span className="text-cyan-300">{icon}</span><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[.04] p-2"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>; }
