import DashboardLayout from "@/components/DashboardLayout";
import React, { useMemo, useState } from "react";
import { SectionTitle, StatusPill } from "@/components/finance-ui";
import { trpc } from "@/lib/trpc";
import { BarChart3, Filter, GitCompareArrows, Search, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function Analysts() {
  const analysts = trpc.capitalguard.discoverAnalysts.useQuery();
  const [selected, setSelected] = useState<string[]>([]);
  const [search, setSearch] = useState("");
  const [onlyEligible, setOnlyEligible] = useState(false);
  const [sortBy, setSortBy] = useState<"pnl" | "win_rate" | "drawdown" | "profit_factor">("pnl");
  const rows = analysts.data?.items ?? [];
  const visibleRows = useMemo(() => {
    const needle = search.trim().toLowerCase();
    return [...rows]
      .filter(row => !onlyEligible || row.eligible_for_ranking)
      .filter(row => !needle || `${row.public_name} ${row.analyst_code ?? ""} ${row.public_ref ?? ""}`.toLowerCase().includes(needle))
      .sort((a, b) => {
        if (sortBy === "win_rate") return b.win_rate_pct - a.win_rate_pct || b.sample_size - a.sample_size;
        if (sortBy === "drawdown") return a.max_drawdown_pct - b.max_drawdown_pct || b.total_pnl_pct - a.total_pnl_pct;
        if (sortBy === "profit_factor") return (b.profit_factor ?? (b.profit_factor_infinite ? Number.POSITIVE_INFINITY : 0)) - (a.profit_factor ?? (a.profit_factor_infinite ? Number.POSITIVE_INFINITY : 0));
        return b.total_pnl_pct - a.total_pnl_pct || b.win_rate_pct - a.win_rate_pct;
      });
  }, [rows, search, onlyEligible, sortBy]);
  const selectedRows = useMemo(() => rows.filter(row => selected.includes(row.analyst_code ?? row.public_ref ?? "")), [rows, selected]);
  const comparison = trpc.capitalguard.compareAnalysts.useQuery({ codes: selected }, { enabled: selected.length >= 2, refetchOnWindowFocus: true });
  const toggle = (code: string) => setSelected(current => current.includes(code) ? current.filter(item => item !== code) : current.length < 3 ? [...current, code] : current);

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-[1380px]">
    <div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Analyst Discovery</p><h1 className="text-3xl font-semibold">اكتشف الأداء. ثم قارن السياق.</h1><p className="mt-2 text-sm text-muted-foreground">المقارنة تعتمد بيانات Core العامة فقط؛ وتبقى أهلية الترتيب مرتبطة بالعينة والتحقق.</p></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><AnalystSignal icon={<ShieldCheck/>} label="قابلون للترتيب" value={String(rows.filter(row => row.eligible_for_ranking).length)}/><AnalystSignal icon={<BarChart3/>} label="محللون في Core" value={String(rows.length)}/><AnalystSignal icon={<GitCompareArrows/>} label="مختارون للمقارنة" value={String(selected.length)}/></div>
    <section className="rounded-3xl border border-white/8 bg-card/70 p-5"><SectionTitle title="لوحة المحللين" action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><Search className="h-4 w-4"/>اختر حتى ثلاثة محللين للمقارنة</div>}/>
      <div className="mt-4 grid gap-3 rounded-2xl border border-white/8 bg-white/[.02] p-4 md:grid-cols-[1fr_180px_auto]"><label className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-950/50 px-3 py-2"><Search className="h-4 w-4 text-muted-foreground"/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث بالاسم أو الرمز" className="w-full bg-transparent text-sm outline-none"/></label><select value={sortBy} onChange={event => setSortBy(event.target.value as typeof sortBy)} className="rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2 text-sm"><option value="pnl">الترتيب حسب PnL</option><option value="win_rate">الترتيب حسب Win Rate</option><option value="drawdown">الأقل Drawdown</option><option value="profit_factor">Profit Factor</option></select><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={onlyEligible} onChange={event => setOnlyEligible(event.target.checked)} className="h-4 w-4 accent-cyan-400"/><Filter className="h-4 w-4"/> المؤهلون فقط</label></div>
      {analysts.isLoading ? <p className="py-8 text-sm text-muted-foreground">جارٍ تحميل المحللين من Core…</p> : analysts.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب بيانات المحللين الحية. لم تُعرض بيانات بديلة.</p> : rows.length === 0 ? <p className="mt-4 rounded-2xl border border-white/8 bg-white/[.025] p-4 text-sm text-muted-foreground">لا توجد ملفات محللين عامة متاحة حالياً.</p> : visibleRows.length === 0 ? <p className="mt-4 rounded-2xl border border-white/8 bg-white/[.025] p-4 text-sm text-muted-foreground">لا توجد نتائج مطابقة للفلاتر الحالية.</p> : <div className="mt-4 grid gap-4 lg:grid-cols-3">{visibleRows.map(analyst => { const code = analyst.analyst_code ?? analyst.public_ref ?? analyst.public_name; const factor = analyst.profit_factor_infinite ? "∞" : analyst.profit_factor == null ? "—" : analyst.profit_factor.toFixed(2); return <article key={code} className={"rounded-2xl border bg-white/[.025] p-5 transition " + (selected.includes(code) ? "border-cyan-400/40" : "border-white/8 hover:border-cyan-400/25")}><div className="flex items-start justify-between"><div><p className="font-mono text-[11px] text-cyan-300">{code}</p><h3 className="mt-2 text-lg font-semibold">{analyst.public_name}</h3><p className="mt-1 text-xs text-muted-foreground">حدّثت قبل {analyst.freshness_days ?? "—"} يوم</p></div><StatusPill value={analyst.eligible_for_ranking ? "verified" : "low_sample"}/></div><div className="mt-5 grid grid-cols-2 gap-2 text-center sm:grid-cols-4"><Metric label="Win Rate" value={`${analyst.win_rate_pct.toFixed(1)}%`}/><Metric label="PnL" value={`${analyst.total_pnl_pct.toFixed(2)}%`}/><Metric label="Drawdown" value={`${analyst.max_drawdown_pct.toFixed(2)}%`}/><Metric label="PF" value={factor}/></div><div className="mt-4 flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">Sample Size: {analyst.sample_size}</p><div className="flex gap-2"><Link href={`/analysts/${encodeURIComponent(code)}`} className="rounded-lg border border-white/10 px-2.5 py-1.5 text-xs text-slate-200">الملف</Link><button onClick={() => toggle(code)} className="rounded-lg bg-white/5 px-2.5 py-1.5 text-xs text-cyan-200">{selected.includes(code) ? "إزالة" : "قارن"}</button></div></div></article>; })}</div>}
    </section>
    {selectedRows.length >= 2 ? <section className="mt-6 rounded-3xl border border-cyan-400/15 bg-gradient-to-l from-cyan-400/[.08] to-violet-400/[.07] p-5"><SectionTitle eyebrow="Compare Analysts" title="نتيجة المقارنة الحية"/>{comparison.isLoading ? <p className="py-5 text-sm text-muted-foreground">جارٍ حساب المقارنة من بيانات Core…</p> : comparison.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر حساب المقارنة الحية. أعد المحاولة بعد التحقق من اتصال Core.</p> : comparison.data ? <><div className="mb-4 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span>الصدارة: {comparison.data.leader?.analystCode ?? "غير متاحة"}</span><span>الثقة: {comparison.data.confidence === "SUFFICIENT_SAMPLE" ? "عينة كافية" : "عينة محدودة"} · قراءة {new Date(comparison.data.asOf).toLocaleString("ar-SA")}</span></div><div className="grid gap-3 md:grid-cols-3">{comparison.data.rows.map((row, index) => <div key={row.analystCode} className="rounded-2xl border border-white/8 bg-background/40 p-4"><p className="font-mono text-xs text-cyan-200">{row.analystCode}</p><p className="mt-2 text-lg font-semibold">{index === 0 ? "الصدارة الحالية" : "ضمن المقارنة"}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Metric label="PnL" value={`${row.totalPnlPct.toFixed(2)}%`}/><Metric label="Win Rate" value={`${row.winRate.toFixed(1)}%`}/></div><p className="mt-3 text-xs text-muted-foreground">Sample: {row.sampleSize} · DD: {row.maxDrawdownPct.toFixed(2)}%</p></div>)}</div></> : null}</section> : null}
  </div></DashboardLayout>;
}
function AnalystSignal({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-white/8 bg-card/70 p-4"><span className="text-cyan-300">{icon}</span><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[.04] p-2"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>; }
