import DashboardLayout from "@/components/DashboardLayout";
import { SectionTitle, StatusPill } from "@/components/finance-ui";
import { trpc } from "@/lib/trpc";
import { CheckCheck, FileClock, ShieldAlert } from "lucide-react";

export default function Historical() {
  const historical = trpc.capitalguard.historicalWallet.useQuery();
  const rows = historical.data?.items ?? [];
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-[1380px]">
    <div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-violet-300">Historical Intelligence</p><h1 className="text-3xl font-semibold">الزمن ليس ملاحظة. إنه محرك القرار.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">قراءة معزولة من Core لسجل المتابعة التاريخي فقط؛ لا تحول هذه الشاشة أي سجل إلى توصية أو UserTrade حي.</p></div>
    <div className="grid gap-4 md:grid-cols-3"><Mini icon={<FileClock/>} title="Temporal Router" detail="يفصل Live وHistorical وفق عمر المصدر وصلاحية السعر."/><Mini icon={<ShieldAlert/>} title="Financial Reconciliation" detail="يحجز تضارب PnL أو ترتيب الأحداث للمراجعة."/><Mini icon={<CheckCheck/>} title="Owner Review" detail="الاعتماد الصريح يسبق Evidence Ingestion دائمًا."/></div>
    <section className="mt-6 rounded-3xl border border-white/8 bg-card/70 p-5"><SectionTitle eyebrow="Core Historical Read Model" title="سجل المتابعة التاريخي" action={historical.data?.as_of ? <span className="text-xs text-violet-200">تحديث {new Date(historical.data.as_of).toLocaleString("ar-SA")}</span> : undefined}/>{historical.isLoading ? <p className="py-8 text-sm text-muted-foreground">جارٍ تحميل السجل التاريخي من Core…</p> : historical.isError ? <p className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-100">تعذر جلب السجل التاريخي الحي. لم تُعرض دفعات عرض بديلة.</p> : rows.length === 0 ? <p className="rounded-2xl border border-white/8 bg-white/[.025] p-4 text-sm text-muted-foreground">لا توجد إشارات تاريخية منسوبة إلى هذا الحساب حالياً.</p> : <><div className="grid gap-3 md:hidden">{rows.map(record => <HistoryCard key={record.public_ref} record={record}/>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-right"><thead className="text-[11px] uppercase tracking-[.12em] text-muted-foreground"><tr><th className="pb-3">السجل</th><th className="pb-3">الأصل</th><th className="pb-3">الاتجاه</th><th className="pb-3">الحالة</th><th className="pb-3">الثقة</th><th className="pb-3">الترتيب</th><th className="pb-3">وقت القرار</th></tr></thead><tbody>{rows.map(record => <tr key={record.public_ref} className="border-t border-white/6 text-sm"><td className="py-4 font-mono text-xs text-violet-200">{record.public_ref}</td><td className="py-4 font-medium">{record.asset ?? "—"}</td><td className="py-4">{record.side ?? "—"}</td><td className="py-4"><StatusPill value={record.status}/></td><td className="py-4"><StatusPill value={record.trust_tier}/></td><td className="py-4">{record.eligible_for_ranking ? "مؤهل" : "غير مؤهل"}</td><td className="py-4 text-xs text-muted-foreground">{record.decision_timestamp ? new Date(record.decision_timestamp).toLocaleString("ar-SA") : "—"}</td></tr>)}</tbody></table></div></>}</section>
  </div></DashboardLayout>;
}
function HistoryCard({ record }: { record: { public_ref: string; asset: string | null; side: string | null; status: string; trust_tier: string; eligible_for_ranking: boolean; decision_timestamp: string | null } }) { return <article className="rounded-2xl border border-white/7 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[11px] text-violet-200">{record.public_ref}</p><p className="mt-1 text-sm font-medium">{record.asset ?? "—"} · {record.side ?? "—"}</p></div><StatusPill value={record.status}/></div><div className="mt-3 flex flex-wrap gap-2"><StatusPill value={record.trust_tier}/><span className="text-xs text-muted-foreground">{record.eligible_for_ranking ? "مؤهل للترتيب" : "غير مؤهل"}</span></div></article>; }
function Mini({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="rounded-2xl border border-white/8 bg-card/70 p-5"><span className="inline-flex rounded-xl bg-violet-400/10 p-2 text-violet-300">{icon}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
